apiVersion: apps/v1
kind: Deployment
metadata:
  name: xt-wsock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xt-wsock
  template:
    metadata:
      labels:
        app: xt-wsock
    spec:
      # 노드 친화성 및 테인트 설정
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values: ["access-layer"]
      tolerations:
      - key: "group"
        operator: "Equal"
        value: "access"
        effect: "NoSchedule"

      containers:
      # (1) Nginx (WebSocket 전용 설정)
      - name: nginx
        image: 211.240.28.240:30081/platform-development-team/xt-wsock-nginx:8d1a2f6f
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"     # 0.05 코어 (이걸 기준으로 % 계산)
            memory: "128Mi"
          limits:
            cpu: "1000m"    # 최대 0.2 코어
            memory: "512Mi"
        # [추가 1] Nginx를 바로 켜지 않고, 설정 생성 스크립트를 먼저 실행합니다.
        command: ["/bin/bash", "/home/xt_rest/run_nginx.sh"]
        ports:
        - containerPort: 30046
        # [추가 2] 스크립트에게 "프로세스가 6개다"라고 알려줍니다.
        env:
        - name: PROCESS_COUNT
          value: "6"
        - name: TZ
          value: "Asia/Seoul"  # 추가
        volumeMounts:
        - name: app-config-vol
          mountPath: /home/xt_rest/acs/env/XtWSOCK.cfg
          subPath: XtWSOCK.cfg
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx-wsock.conf
        - name: shared-socket-vol
          mountPath: /var/run/xt

      # (2) XtWSOCK
      - name: xt-wsock-app
        image: 211.240.28.240:30081/platform-development-team/access-wsock:ff0d9a7
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "Asia/Seoul"  # 추가
        resources:
          requests:
            cpu: "100m"     # 0.05 코어 (이걸 기준으로 % 계산)
            memory: "256Mi"
          limits:
            cpu: "1000m"    # 최대 0.2 코어
            memory: "1Gi"
        # Nginx와 localhost 통신
        volumeMounts:
        - name: shared-socket-vol
          mountPath: /var/run/xt

      volumes:
      - name: app-config-vol
        configMap:
          name: access-config
          items:
          - key: XtWSOCK.cfg      # ConfigMap 안의 키 이름
            path: XtWSOCK.cfg     # 파일로 저장될 이름

      - name: config-volume       # (기존 Nginx 설정용)
        configMap:
          name: access-config

      - name: shared-socket-vol   # (소켓 공유용)
        emptyDir: {}
