apiVersion: apps/v1
kind: Deployment
metadata:
  name: xt-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xt-rest
  template:
    metadata:
      labels:
        app: xt-rest
    spec:
      # 노드 친화성 및 테인트 설정
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values: ["access-layer"]
      tolerations:
      - key: "group"
        operator: "Equal"
        value: "access"
        effect: "NoSchedule"

      containers:
      # (1) Nginx (REST 전용 설정)
      - name: nginx
        image: 211.240.28.240:30081/platform-development-team/xt-rest-nginx:8d1a2f6f
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"     # 0.05 코어 (이걸 기준으로 % 계산)
            memory: "64Mi"
          limits:
            cpu: "200m"    # 최대 0.2 코어
            memory: "128Mi"
        ports:
        - containerPort: 30145
        - containerPort: 30045
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx-rest.conf
        - name: shared-socket-vol
          mountPath: /var/run/xt

      # (2) XtREST
      - name: xt-rest-app
        image: 211.240.28.240:30081/platform-development-team/access-rest:e74c2ff
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"     # 0.05 코어 (이걸 기준으로 % 계산)
            memory: "64Mi"
          limits:
            cpu: "200m"    # 최대 0.2 코어
            memory: "128Mi"
        # Nginx와 localhost 통신
        volumeMounts:
        - name: shared-socket-vol
          mountPath: /var/run/xt

      volumes:
      - name: config-volume
        configMap:
          name: access-config
      - name: shared-socket-vol
        emptyDir: {}  # 메모리 기반 임시 볼륨

