apiVersion: v1
kind: Service
metadata:
  name: access-rest-svc
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: xt-rest
  ports:
  # 사용하는 모든 포트를 나열합니다.
  - name: main
    port: 40145
    targetPort: 30145
  - name: fcgi-01
    port: 40045
    targetPort: 30045
