apiVersion: v1
kind: Service
metadata:
  name: dest-direct-svc # 이름은 기존 dest-svc와 다르게
spec:
  type: LoadBalancer    # 외부에서 직접 접속용 로드밸런서
  externalTrafficPolicy: Local # [필수] 클라이언트 진짜 IP 보존 & 성능 최적화
  selector:
    app: dest           # dest-svc처럼 목적 파드에 동일하게 연결
  ports:
  - name: data-stream
    protocol: TCP
    port: 9000          # 외부에서 접속할 포트 (예: 9000번)
    targetPort: 80      # 목적 파드의 실제 포트
