apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dev5-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: node-exporter
  endpoints:
    - port: metrics
      interval: 15s
    - port: process-metrics
      interval: 15s
