apiVersion: v1
kind: Service
metadata:
  name: dev5-metrics
  namespace: monitoring
  labels:
    release: prometheus
    app: node-exporter
spec:
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
    - name: process-metrics
      port: 9256
      targetPort: 9256
---
apiVersion: v1
kind: Endpoints
metadata:
  name: dev5-metrics
  namespace: monitoring
subsets:
  - addresses:
      - ip: 211.240.28.248
    ports:
      - name: metrics
        port: 9100
      - name: process-metrics
        port: 9256
