apiVersion: v1
kind: Service
metadata:
  name: my-kafka
spec:
  ports:
    - port: 9092
      name: plaintext
      targetPort: 9092
  selector:
    app: kafka
  clusterIP: None  # Headless Service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      # [핵심] m02 노드에 고정
      nodeSelector:
        kubernetes.io/hostname: minikube-m02
      tolerations:
      - key: "group"          # Taint의 키가 'group'인 경우
        operator: "Exists"    # 값(infra, biz 등)에 상관없이 존재하기만 하면 통과
        effect: "NoSchedule"  # 스케줄링 제한을 무시함
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.6.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092

        # [핵심] KRaft 모드 설정 (주키퍼 없이 실행)
        env:
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://:9092,CONTROLLER://:9093"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://my-kafka:9092"
        - name: KAFKA_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "1@localhost:9093"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: CLUSTER_ID
          value: "MkU3OEVBNTcwNTJENDM2Qk" # 임의의 ID
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_LOG_RETENTION_HOURS
          value: "24"
